apiVersion: v1
kind: Pod
metadata:
  name: conversao-temperatura
  labels:
    name: myapp
spec:
  containers:
  - name: conversao-temperatura
    image: yurilacerda/conversao-temperatura:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        targetPort: 5000
        nodePort: 30000
    type: LoadBalancer  
